### ISSUE TITLE
Getting class-wp-session.php error with EDD

### ISSUE THREAD

**Issue by techjewel** [Awesome-Support/Awesome-Support#724] opened 2019-07-16 09:19 UTC
Hello,
I am getting the following error when WP_DEBUG and WP_DEBUG_LOG enabled.

> [16-Jul-2019 08:30:20 UTC] PHP Warning:  Cannot modify header information - headers already sent in/**/**/wp-content/plugins/awesome-support/vendor/ericmann/wp-session-manager/includes/class-wp-session.php on line 142

I have Easy Digital Downloads plugin installed. If I disabled EDD then i am not getting this error. 

Any help?

**Comment by glagonikas** [comment] 2019-07-29 16:05
I don't think this is caused by EDD. We get the same issue and don't use EDD.

It seems that Awesome Support is using an older version of Eric Mann's WP Session Manager. It uses v2.0.2 when v4.2.0 is available on his repo.

There is already a fix for this as shown at https://github.com/ericmann/wp-session-manager/issues/81 and Awesome Support should simply use the updated version.

**Comment by glagonikas** [comment] 2019-07-30 11:04
Also, this notice appears on WP v5.x.x. It wasn't showing on WP v4.9.x.

**Comment by glagonikas** [comment] 2019-07-30 11:10
One way to suppress the error is by updating /wp-content/plugins/awesome-support/vendor/ericmann/wp-session-manager/includes/class-wp-session.php Line 142 from

```
setcookie( WP_SESSION_COOKIE, $this->session_id . '||' . $this->expires . '||' . $this->exp_variant , $this->expires, COOKIEPATH, COOKIE_DOMAIN, $secure, $httponly );
```
to
```
if ( !headers_sent() ) {
	setcookie( WP_SESSION_COOKIE, $this->session_id . '||' . $this->expires . '||' . $this->exp_variant , $this->expires, COOKIEPATH, COOKIE_DOMAIN, $secure, $httponly );
}
```
It works fine for us, considering the notice only appears when wp-cron.php is called, but it might cause issues for other people.

**Comment by Mohal** [comment] 2022-02-24 05:36
This issue has been resolved with the update of "ericmann/wp-session-manager" to "4.2.0."

**Closed by Mohal** 2022-02-24 05:36 UTC
